# Generated by Django 5.1.1 on 2024-10-10 04:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/books/covers/')),
                ('rating', models.IntegerField(default=0)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='books/pdfs/')),
                ('category', models.CharField(choices=[('library', 'E.Library'), ('BTech', 'B.Tech'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('Degree', 'Degree')], default='library', max_length=10)),
                ('selected_item', models.CharField(blank=True, default='history', max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/students/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
